version: '3.8'

services:
  match_now_server:
    build:
      context: .
      dockerfile: Dockerfile.dev  # 개발용 Dockerfile 사용
    container_name: match_now_server
    ports:
      - "3701:3701"
    volumes:
      # 소스코드 볼륨 마운트 (핫 리로드)
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3701
      # macOS/Windows에서 파일 변경 감지 향상
      - CHOKIDAR_USEPOLLING=true
    # 데이터베이스 의존성 제거 (현재 사용하지 않으므로)
    # depends_on:
    #   - database
    restart: unless-stopped
      
  # 데이터베이스는 주석 처리 (필요할 때 활성화)
  # database:
  #   image: mysql:8.0
  #   container_name: match_now_db
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_DATABASE: match_now
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - db_data:/var/lib/mysql

# volumes:
#   db_data: