version: '3.8'

services:
  match_now_server:
    build: .
    container_name: match_now_server
    ports:
      - "3701:3701"
    volumes:
      # 소스코드 볼륨 마운트 (핫 리로드)
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    # 파일 변경 감지하여 자동 재시작
    command: npm run start:dev
    # 의존성 서비스가 있다면
    depends_on:
      - database
      
  database:
    image: mysql:8.0
    container_name: match_now_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: match_now
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: