version: '3.8'

services:
  match_now_server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: match_now_server
    ports:
      - "3701:3701"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3701
      - CHOKIDAR_USEPOLLING=true
      # 인증이 포함된 MongoDB URI
      - MONGODB_URI=mongodb://matchuser:matchpass123@mongodb:27017/match_now_db?authSource=match_now_db
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - match_now_network

  mongodb:
    image: mongo:7.0
    container_name: match_now_mongodb
    ports:
      - "27017:27017"
    environment:
      # 특정 데이터베이스에 사용자 생성
      - MONGO_INITDB_DATABASE=match_now_db
    volumes:
      - mongodb_data:/data/db
      - ./docker-init/mongo-init-auth.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    healthcheck:
      test: ["CMD", "mongosh", "match_now_db", "--eval", "db.adminCommand('ping')"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - match_now_network

volumes:
  mongodb_data:
    driver: local

networks:
  match_now_network:
    driver: bridge